sudo: required
services: 
  - docker

before_install:
  - docker build -t lucasavs/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lucasavs/react-test npm test -- --coverage

after_sucess:
  - docker build -t lucasavs/multi-client ./client
  - docker build -t lucasavs/multi-nginx ./nginx
  - docker build -t lucasavs/multi-server ./server
  - docker build -t lucasavs/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push lucasavs/multi-client
  - docker push lucasavs/multi-nginx
  - docker push lucasavs/multi-server
  - docker push lucasavs/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket: "elasticbeanstalk-sa-east-1-033536126395"
  bucket_name: "elasticbeanstalk-sa-east-1-033536126395"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"